query lists($limit: Int, $offset: Int) {
	confessions {
		author {
      id
      name
      nickname
    }
    id
    involved {
      id
      name
      nickname
    }
    links
    longText
    money
    shortText
    when
	},
  characters(limit: $limit, offset: $offset) {
		avatar
		id
		name
		nickname
	}
}